#cloud-config

# update package database on first boot (apt-get update)
package_update: true

# upgrade the instance on first boot (apt-get upgrade)
package_upgrade: true

packages:
  - wget
  - curl
  - git
  - htop
  - build-essential
  - zsh

# sets the hostname to 'ubuntu-vm'
hostname: ubuntu-vm

# sh-keygen -b 2048 -f ~/.ssh/multipass -t rsa -q -N ""
# cat ~/.ssh/multipass.pub
sh-authorized-keys:
 - <ssh-rsa>
 
runcmd:
 - runuser -l ubuntu -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' 
 - chsh -s $(which zsh) ubuntu
 - fgGreen='%{$fg[green]%}'
 - fgCyan='%{$fg[cyan]%}'
 - fgReset='%{$reset_color%}'
 - retStatus='${ret_status}'
 - gitInfo='$(git_prompt_info)'
 - runuser -l ubuntu -c "echo export PROMPT=\''${fgGreen}%n@%m${fgReset} ${retStatus} ${fgCyan}%c${fgReset} ${gitInfo}'\'" >> /home/ubuntu/.zshrc
 - echo "source ~/.profile" >> /home/ubuntu/.zshrc